spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/dasqr
    username: postgres
    password: password
    type: org.springframework.jdbc.datasource.SimpleDriverDataSource
  flyway:
    enabled: true
    locations: classpath:flyway
    sql-migration-prefix: v
    table: core_flyway_schema
logging:
  level:
    root: info
    net.mamoe.mirai: info
    com.dasoops.dasqr: info
    com.dasoops.common: info
    com.dasoops.common.cache: info
  file:
    path: /temp/dasqr/logs/dasqr.log
  register-shutdown-hook: true
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 60
      total-size-cap: 8GB
      clean-history-on-start: true
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
    console: "%clr(%-5level) %clr(%d{yy-MM-dd HH:mm:ss}){cyan} %clr([%-26thread]){cyan} %clr(%-20logger{0}){yellow} : %msg%n"
mirai:
  bot:
    qq: 3488521150
    password: password
    type: byQrCode
    protocol: android_phone
  file:
    device-info-path: device.json
    cache-path: cache
    workingDir: .
  log:
    useLog4j2: true
dasqr:
  exception:
    exclude-class:
      - com.dasoops.dasqr.core.templateExcludeClass
    scan-path:
      - com.dasoops.dasqr.core
  plugin:
    path: ./plugin
    scan-path:
      - com.dasoops.dasqr.core
      - com.dasoops.dasqr.plugin