server:
  port: 4701

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dasq?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=true&allowMultiQueries=true
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:

logging:
  level:
    com:
      dasoops:
        dasq:
          core: debug

minio:
  enable: true
  url: 106.13.5.29
  port: 9000
  bucket: dasqserver
  accessKey: aaaaa
  secretKey: aaaaaaaa
  tempDownloadPath: D:\temp

mybatis-plus:
  global-config:
    db-config:
      # 全局逻辑删除的实体字段名
      logic-delete-field: isDelete

dasq:
  # 控制台打印异常堆栈信息
  consolePrintStack: true
  # java端访问token
  token: dasKi
  # cqhttp url地址
  cqHttpUrl: http://127.0.0.1:4700
  # cq OAUTH2 access-token
  cqToken: dasKi
  # DasServer版本号
  version: "049"
  # 开发群id
  devGroupId: 673745932
  # 主开发者id
  adminId: 776465218
  # 是否为demo版本
  isDemo: true
  # 命令样式 cool/normal
  style: cool
  # reboot sh 脚本路径
  rebootShellPath: /usr/local/gitRepo/dasServer/reboot.sh